force-app/main/default/objects/Data_Summary__c/Data_Summary__c.object-meta.xml
<CustomObject>
    <label>Data Summary Task</label>
    <nameField>
        <displayFormat>ds-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Date_Field_on_Child_Record__c.field-meta.xml
<CustomField>
    <fullName>Date_Field_on_Child_Record__c</fullName>
    <inlineHelpText>The field on the child record containing the date to base the analysis on</inlineHelpText>
    <label>Date Field on Child Record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A description that explains the intent of the task for you and your team</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Analysis Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily - Current</fullName>
            </value>
            <value>
                <fullName>Daily - Previous</fullName>
            </value>
            <value>
                <fullName>Monthly - Current</fullName>
            </value>
            <value>
                <fullName>Monthly - Previous</fullName>
            </value>
            <value>
                <fullName>Quarterly - Current</fullName>
            </value>
            <value>
                <fullName>Quarterly - Previous</fullName>
            </value>
            <value>
                <fullName>Yearly - Current</fullName>
            </value>
            <value>
                <fullName>Yearly - Previous</fullName>
            </value>
            <value>
                <fullName>FY - Current</fullName>
            </value>
            <value>
                <fullName>FY - Previous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>The object that serves as the &quot;root&quot; of all data to be analyzed.  Often this will be the Contact object</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Date_Field__c</fullName>
    <label>Snapshot Date Field (on snapshot object)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Object__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Object__c</fullName>
    <inlineHelpText>The object where snapshots will be created</inlineHelpText>
    <label>Snapshot Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/Data_Summary_Field__c.object-meta.xml
<CustomObject>
    <label>Data Summary Field</label>
    <nameField>
        <displayFormat>dsf-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary_Field__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <formula>if (!isblank(Summary__r.Child_Object__c), Summary__r.Child_Object__c, Summary__r.Parent_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Child Object, as set on the Summary Task</inlineHelpText>
    <label>Child Object (as set on the task)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/How_to_Summarize__c.field-meta.xml
<CustomField>
    <fullName>How_to_Summarize__c</fullName>
    <inlineHelpText>How you’d like the data summarized</inlineHelpText>
    <label>How to Summarize</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>count</fullName>
            </value>
            <value>
                <fullName>sum</fullName>
            </value>
            <value>
                <fullName>min</fullName>
            </value>
            <value>
                <fullName>max</fullName>
            </value>
            <value>
                <fullName>average</fullName>
            </value>
            <value>
                <fullName>oldest value</fullName>
            </value>
            <value>
                <fullName>newest value</fullName>
            </value>
            <value>
                <fullName>copy (including blanks)</fullName>
            </value>
            <value>
                <fullName>copy (only non-blank)</fullName>
            </value>
            <value>
                <fullName>Count Unique Values</fullName>
            </value>
            <value>
                <fullName>Count Unique Values (ignore case)</fullName>
            </value>
            <value>
                <fullName>Median</fullName>
            </value>
            <value>
                <fullName>Standard Deviation (population)</fullName>
            </value>
            <value>
                <fullName>Standard Deviation (sample)</fullName>
            </value>
            <value>
                <fullName>List Unique Values</fullName>
            </value>
            <value>
                <fullName>List Unique Values (ignore case)</fullName>
            </value>
            <value>
                <fullName>Set Specific Value</fullName>
                <isActive>false</isActive>
                <label>Set Specific Value</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field (on Child)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Specific_Value_to_Set__c.field-meta.xml
<CustomField>
    <fullName>Specific_Value_to_Set__c</fullName>
    <label>Specific Value to Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary Task</label>
    <referenceTo>Data_Summary__c</referenceTo>
    <relationshipLabel>Data Summary Fields</relationshipLabel>
    <relationshipName>Data_Summary_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>The field where the analysis will be stored</inlineHelpText>
    <label>Summarize To (Target Field)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataSummaries_test.cls
/*
*  Steve Berley - steve@leftpropeller.com
*
*  IMPORTANT:  The challenge when creating data for testing is to use factory fields provided with core Salesforce.  This means none
*  that end in __c.  Doing so will make the code easier to move between orgs since you don't have to worry about whether fields exist.
*
*/
@isTest 
public class DataSummaries_test {
    public static string snapObj = 'asset';

    @isTest static void test_one(){
        // tests: echo, sum
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'name', 'copy (including blanks)') );
        fields.add( genField(st.id, 'amount', 'quantity', 'sum') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_one');
        
        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }


    @isTest static void test_two(){
        // tests: echo, average
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'name', 'copy (including blanks)') );
        fields.add( genField(st.id, 'amount', 'quantity', 'average') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_two');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }



    @isTest static void test_three(){
        // tests: oldest and count
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'name', 'oldest value') );
        fields.add( genField(st.id, 'amount', 'quantity', 'count') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_three');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }


    @isTest static void test_count(){
        // tests:  count
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'amount', 'quantity', 'count') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_count');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }


    @isTest static void test_uniques(){
        // tests:  count
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'quantity', 'count unique values (ignore case)' ) );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_uniques');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    } 


    @isTest static void test_median(){
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'name', 'copy (including blanks)') );
        fields.add( genField(st.id, 'amount', 'quantity', 'median') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_median');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }

    
    @isTest static void test_oldest(){
        // tests: oldest 
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'name', 'oldest value') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_oldest');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }


    @isTest static void test_newest(){
        // tests: newest 
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'name', 'newest value') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_newest');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }


    @isTest static void test_max(){
        // tests: max
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'amount', 'quantity', 'max') );
        // fields.add( genField(st.id, 'closedate', 'installdate', 'newest value') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_max');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }


    @isTest static void test_min(){
        // tests: min
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'amount', 'quantity', 'min') );
        // fields.add( genField(st.id, 'closedate', 'installdate', 'newest value') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_min');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }
    

    @isTest static void test_stdDev(){
        // tests: just tests standard deviations
        createData();
        Data_Summary__c st = createSummaryObj(snapObj);

        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'amount', 'quantity', 'standard deviation (sample)') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_stdDev');

        test.startTest();
            DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
        test.stopTest();
    }

    
    // @isTest static void test_setValue(){
    //     // tests: set value
    //     createData();
    //     Data_Summary__c st = createSummaryObj(snapObj);
    //     list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
    //     Data_Summary_Field__c stamper = genField(st.id, 'name', 'name', 'set specific value');
    //     stamper.Specific_Value_to_Set__c = 'hello sweetie';
    //     fields.add( stamper );
    //     insert fields;

    //     verifyConfigDataSetup(st.id, 'test_setValue');

    //     test.startTest();
    //         DataSummaries.DataSummariesInvocable( new list<string>{st.id} );
    //     test.stopTest();
    // }


    @isTest static void test_clearFields(){
        Data_Summary__c st = createSummaryObj(snapObj);
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        fields.add( genField(st.id, 'name', 'name', 'copy (including blanks)') );
        fields.add( genField(st.id, 'amount', 'quantity', 'sum') );
        // fields.add( genField(st.id, 'closedate', 'installdate', 'min') );
        insert fields;
        verifyConfigDataSetup(st.id, 'test_clearFields');

        list<Opportunity> opps = createData();

        summaryTask task = new summaryTask(st.id);
        test.startTest();
            DataSummaries ds = new DataSummaries(null);
            ds.clearFields( database.query(task.outliersQuery) );
        test.stopTest();     
    }


    @isTest static void test_isChanged(){
        DataSummaries dss = new DataSummaries(null);
        string x = 'helloooo';
        string y = 'sweetie';
        dss.isChanged(x,y);
    }
     

    public static void verifyConfigDataSetup(id summaryID, string test){
        summaryTask st = new summaryTask(summaryID);
        system.assert( !string.isblank(st.parentQuery), '>>>>>>    config data load failure!!!  '+test  );
    }


    public static list<opportunity> createData(){
        account a = new account(name='test account');
        insert a;
        date yesterday = date.today().addDays(-1);

        list<opportunity> opps = new list<opportunity>();
        opps.add( new opportunity(accountid = a.id, amount = 12.34, name='xx', closedate=yesterday,stagename='closed won'));
        opps.add( new opportunity(accountid = a.id, amount = 22.34, name='xx', closedate=yesterday,stagename='closed won'));
        opps.add( new opportunity(accountid = a.id, amount = 33.34, name='xx', closedate=date.newInstance(1966,9,26),stagename='closed won'));
        opps.add( new opportunity(accountid = a.id, amount = 44.34, name='xx', closedate=date.today(),stagename='closed won'));
        insert opps;
        
        summaryTask st = new summaryTask(null);
        insert new asset(name = 'aa', accountid = a.id, installdate = st.snapdate);
        return opps;
    }


    public static Data_Summary_Field__c genField(id summary, string source, string target, string action){
        return new Data_Summary_Field__c(summary__c = summary, Source_Field__c = source, target_field__c = target, How_to_Summarize__c = action);
    }


    public static Data_Summary__c createSummaryObj(string snapObj){
        Data_Summary__c ds = new Data_Summary__c();
        ds.Description__c = 'data summary for testing';
        ds.Parent_Object__c = 'Account';
        ds.Frequency__c = 'Daily - Previous';
        ds.Child_Object__c = 'Opportunity';
        ds.Date_Field_on_Child_Record__c = 'closedate';
        if ( string.isNotBlank(snapObj) ) {
            ds.Snapshot_Object__c = snapObj;
            ds.Snapshot_Date_Field__c = 'PurchaseDate';
        }
        insert ds;
        return ds;
    }
}