force-app/main/default/objects/Data_Summary__c/Data_Summary__c.object-meta.xml
<CustomObject>
    <label>Data Summary Task</label>
    <nameField>
        <displayFormat>ds-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Child_Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Name__c</fullName>
    <label>Child Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>The object that serves as the &quot;root&quot; of all data to be analyzed.  Often this will be the Contact object</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Relationship_Field_Child__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field_Child__c</fullName>
    <label>Relationship Field (on Child)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Relationship_Field_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field_Snapshot__c</fullName>
    <inlineHelpText>The field on the Snapshot Object that relates it to the Parent Object (automatic)</inlineHelpText>
    <label>Relationship Field (on Snapshot)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Date_Field__c</fullName>
    <label>Snapshot Date Field (on snapshot object)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Date_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Date_Field_Type__c</fullName>
    <label>Snapshot Date Field Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Object__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Object__c</fullName>
    <inlineHelpText>The object where snapshots will be created</inlineHelpText>
    <label>Snapshot Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Relationship_Name__c</fullName>
    <label>Snapshot Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Where_Clause__c</fullName>
    <label>Where Clause (filters child obj records)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DataSummaryHandler.cls
/*
*  Steve Berley - steve@leftpropeller.com
*/
public with sharing class DataSummaryHandler {
    // public DataSummaryTriggerHandler() { }
    
    public static void autoSetVals(Data_Summary__c ds, Data_Summary__c dsOld){
        boolean objectChanged = false;
        if (dsOld == null || string.isblank(dsOld.LeftProp_DSS__Parent_Object__c) || ds.LeftProp_DSS__Parent_Object__c != dsOld.LeftProp_DSS__Parent_Object__c ) objectChanged = true;
        if (dsOld == null || string.isblank(dsOld.LeftProp_DSS__Child_Object__c) || ds.LeftProp_DSS__Child_Object__c != dsOld.LeftProp_DSS__Child_Object__c ) objectChanged = true;


        // if either the parent or child object has a value and the other is blank - make them the same
        if ( !string.isBlank(ds.LeftProp_DSS__Parent_Object__c) && string.isBlank(ds.LeftProp_DSS__Child_Object__c)){
            ds.LeftProp_DSS__Child_Object__c = ds.LeftProp_DSS__Parent_Object__c;
        }
        else if ( string.isBlank(ds.LeftProp_DSS__Parent_Object__c) && !string.isBlank(ds.LeftProp_DSS__Child_Object__c)){ 
            ds.LeftProp_DSS__Parent_Object__c = ds.LeftProp_DSS__Child_Object__c;
        }


        if ( string.isBlank(ds.Child_Object__c) ) {
            // if child is child is still blank - make it null
            ds.Child_Relationship_Name__c = null;
            ds.Relationship_Field_Child__c = null;
        }        
        else if (ds.LeftProp_DSS__Parent_Object__c == ds.LeftProp_DSS__Child_Object__c) {
            // if both the parent and child objects are the same object, then both fields below are 'id'
            ds.Relationship_Field_Child__c = 'id';
            ds.Child_Relationship_Name__c = 'id';
        }
        else {          
            summaryTask.RelInfo childRel = summaryTask.genRelInfo(ds.Parent_Object__c, ds.Child_Object__c);
            if ((ds.Relationship_Field_Child__c == null && childRel.rel != null) || objectChanged ) ds.Relationship_Field_Child__c = childRel.rel;
            if ((ds.Child_Relationship_Name__c == null && childRel.crn != null) || objectChanged) ds.Child_Relationship_Name__c = childRel.crn;       
        }


        if ( string.isBlank(ds.Snapshot_Object__c) ) {
            ds.Relationship_Field_Snapshot__c = null;
            ds.Snapshot_Relationship_Name__c = null;
        } 
        else {
            summaryTask.RelInfo snapRel = summaryTask.genRelInfo(ds.Parent_Object__c, ds.Snapshot_Object__c);
            if (ds.Relationship_Field_Snapshot__c == null && snapRel.rel != null) ds.Relationship_Field_Snapshot__c = snapRel.rel;
            if (ds.Snapshot_Relationship_Name__c == null && snapRel.crn != null) ds.Snapshot_Relationship_Name__c = snapRel.crn;                    
        }
        
        if ( string.isNotEmpty(ds.Where_Clause__c) ) ds.Where_Clause__c = summaryTask.tuneWhereClause(ds.Where_Clause__c);

        if (ds.Snapshot_Object__c != null && ds.Snapshot_Date_Field__c != null ) {
            ds.Snapshot_Date_Field_Type__c = lpTools.getFieldType(ds.Snapshot_Object__c, ds.Snapshot_Date_Field__c);
        } else ds.Snapshot_Date_Field_Type__c = null;
    }
}