force-app/main/default/objects/Data_Summary__c/Data_Summary__c.object-meta.xml
<CustomObject>
    <label>Data Summary Task</label>
    <nameField>
        <displayFormat>ds-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A description that explains the intent of the task for you and your team</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>The object that serves as the &quot;root&quot; of all data to be analyzed.  Often this will be the Contact object</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Date_Field__c</fullName>
    <label>Snapshot Date Field (on snapshot object)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Object__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Object__c</fullName>
    <inlineHelpText>The object where snapshots will be created</inlineHelpText>
    <label>Snapshot Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <label>Timestamp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current Timeframe</fullName>
                <default>true</default>
                <label>Current Timeframe</label>
            </value>
            <value>
                <fullName>Previous Timeframe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Where_Clause__c</fullName>
    <label>Where Clause (filters child obj records)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DataSummaryHandler_test.cls
/*
*  Steve Berley - steve@leftpropeller.com
*/
@isTest
private with sharing class DataSummaryHandler_test {

    @isTest private static void test_autoSetVals(){
        Data_Summary__c ds = new Data_Summary__c(Description__c='test', Parent_Object__c='Account', Child_Object__c='Contact', Snapshot_Object__c='Opportunity', Snapshot_Date_Field__c = 'closedate');
        insert ds;

        ds.Child_Object__c = null;
        ds.Snapshot_Object__c = null;
        update ds;
    }

    // @isTest private static void test_setDefaultTimestamp(){
    //     Data_Summary__c ds = new Data_Summary__c(timestamp__c = '', where_clause__c = 'date__c = last_month ');
    //     insert ds;

    //     ds.where_clause__c = 'date__c != null';
    //     update ds;
    // }
}