force-app/main/default/objects/Data_Summary__c/Data_Summary__c.object-meta.xml
<CustomObject>
    <label>Data Summary Task</label>
    <nameField>
        <displayFormat>ds-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This acts as an on/off switch allowing you to configure and test tasks before they go live.  When you click Run Summary Now the task will run even if inactive.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Child_Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Name__c</fullName>
    <label>Child Relationship Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Date_Field_on_Child_Record__c.field-meta.xml
<CustomField>
    <fullName>Date_Field_on_Child_Record__c</fullName>
    <inlineHelpText>The field on the child record containing the date to base the analysis on</inlineHelpText>
    <label>Date Field on Child Record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>A description that explains the intent of the task for you and your team</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Analysis Timeframe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily - Current</fullName>
            </value>
            <value>
                <fullName>Daily - Previous</fullName>
            </value>
            <value>
                <fullName>Monthly - Current</fullName>
            </value>
            <value>
                <fullName>Monthly - Previous</fullName>
            </value>
            <value>
                <fullName>Quarterly - Current</fullName>
            </value>
            <value>
                <fullName>Quarterly - Previous</fullName>
            </value>
            <value>
                <fullName>Yearly - Current</fullName>
            </value>
            <value>
                <fullName>Yearly - Previous</fullName>
            </value>
            <value>
                <fullName>FY - Current</fullName>
            </value>
            <value>
                <fullName>FY - Previous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>The object that serves as the &quot;root&quot; of all data to be analyzed.  Often this will be the Contact object</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Process_Data__c.field-meta.xml
<CustomField>
    <fullName>Process_Data__c</fullName>
    <inlineHelpText>If you choose Match Analysis Timeframe and the Analysis Timeframe is Monthly – Current, it’ll run the analysis at the end of every month.  If, however, you set it to Daily, it’ll run the analysis every day of the month, storing it to the end of month record.  While the results will be the same once the month is done, the Daily setting shows you a month-to-date summary as the month progresses where Match just shows you the data once the month is over.</inlineHelpText>
    <label>Process Data</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
                <default>true</default>
                <label>Daily</label>
            </value>
            <value>
                <fullName>Match Analysis Timeframe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Relationship_Field_Child__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field_Child__c</fullName>
    <label>Relationship Field (on Child)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_As_Of_Date__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_As_Of_Date__c</fullName>
    <label>Snapshot As Of Date (blank for auto)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Date_Field__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Date_Field__c</fullName>
    <label>Snapshot Date Field (on snapshot object)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Object__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Object__c</fullName>
    <inlineHelpText>The object where snapshots will be created</inlineHelpText>
    <label>Snapshot Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Where_Clause__c.field-meta.xml
<CustomField>
    <fullName>Where_Clause__c</fullName>
    <label>Where Clause (filters child obj records)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/Data_Summary_Field__c.object-meta.xml
<CustomObject>
    <label>Data Summary Field</label>
    <nameField>
        <displayFormat>dsf-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary_Field__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>This acts as an on/off switch allowing you to control which field summarizations are to be used.When you click Run Summary Now, only the active fields will be processed</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <formula>if (!isblank(Summary__r.Child_Object__c), Summary__r.Child_Object__c, Summary__r.Parent_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Child Object, as set on the Summary Task</inlineHelpText>
    <label>Child Object (as set on the task)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/How_to_Summarize__c.field-meta.xml
<CustomField>
    <fullName>How_to_Summarize__c</fullName>
    <inlineHelpText>How you’d like the data summarized</inlineHelpText>
    <label>How to Summarize</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>count</fullName>
            </value>
            <value>
                <fullName>sum</fullName>
            </value>
            <value>
                <fullName>min</fullName>
            </value>
            <value>
                <fullName>max</fullName>
            </value>
            <value>
                <fullName>average</fullName>
            </value>
            <value>
                <fullName>oldest value</fullName>
            </value>
            <value>
                <fullName>newest value</fullName>
            </value>
            <value>
                <fullName>copy (including blanks)</fullName>
            </value>
            <value>
                <fullName>copy (only non-blank)</fullName>
            </value>
            <value>
                <fullName>Count Unique Values</fullName>
            </value>
            <value>
                <fullName>Count Unique Values (ignore case)</fullName>
            </value>
            <value>
                <fullName>Median</fullName>
            </value>
            <value>
                <fullName>Standard Deviation (population)</fullName>
            </value>
            <value>
                <fullName>Standard Deviation (sample)</fullName>
            </value>
            <value>
                <fullName>List Unique Values</fullName>
            </value>
            <value>
                <fullName>List Unique Values (ignore case)</fullName>
            </value>
            <value>
                <fullName>Set Specific Value</fullName>
                <isActive>false</isActive>
                <label>Set Specific Value</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Reset_Value_After_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Reset_Value_After_Snapshot__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reset Value After Snapshot</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field (on Child)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary Task</label>
    <referenceTo>Data_Summary__c</referenceTo>
    <relationshipLabel>Data Summary Fields</relationshipLabel>
    <relationshipName>Data_Summary_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>The field where the analysis will be stored</inlineHelpText>
    <label>Summarize To (Target Field)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Target_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Type__c</fullName>
    <label>Target Field Type (raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/summaryTask_test.cls
//  Steve Berley - steve@leftpropeller.com
@isTest
public class summaryTask_test {
    public static set<string> frequencies = new set<string>{ 'Daily - Current', 'Daily - Previous', 'Monthly - Current', 'Monthly - Previous', 'Quarterly - Current', 'Quarterly - Previous', 'Yearly - Current', 'Yearly - Previous', 'FY - Current', 'FY - Previous' };
    

    @isTest public static void test_invocable(){
        id taskID = createSummaryObj(null);
        createSummaryPlan(taskID);
        summaryTask.SummaryTaskInvocable(new list<string>{taskID});
    }


    @isTest public static void test_monthEnds(){
        summaryTask st = new summaryTask(null);
        st.lastDayOfMonth(date.today());
        st.lastDayOfPrevMonth(date.today());
    }


    @isTest public static void test_timeframes(){
        set<id> taskIDs = new set<id>();
        for (string f : frequencies) {
            taskIDs.add(createSummaryObj(f));
        }

        for (id t : taskIDs) {
            summaryTask st = new summaryTask(t);
            st.genSnapshotTimestamp();
            st.genQueryTimeString();
        }
    }


    @isTest public static void test_relInfo(){
        summaryTask.genRelInfo('Account', 'Contact');
    }


    @isTest public static void summary_test(){
        id taskID = createSummaryObj(null);
        createSummaryPlan(taskID);
        // createSummaryPlan( createSummaryObj(null) );
 
        test.startTest();
	        summaryTask st = new summaryTask(null);
         	st.endTask();
	        st = new summaryTask(null);
         	st.endTask();
            summaryTask.resetToday();
        test.stopTest();
    }


    @isTest public static void echoMode_test(){
        id taskID = setupEchoTest();

        test.startTest();
	        summaryTask st = new summaryTask(taskID);
         	st.endTask();
	        st = new summaryTask(null);
         	st.endTask();
            summaryTask.resetToday();
        test.stopTest();
    }


    @isTest public static void nulling_test(){
        createSummaryPlan( createSummaryObj(null) );
        summaryTask st = new summaryTask(null);

        if (st.fieldSpecs == null || st.fieldSpecs.size() == 0) return;
        for (Data_Summary_Field__c dsf : st.fieldSpecs.values()) st.getNull(dsf);
    }


    @isTest public static void test_scheduledStart(){
    	summaryTask.start(10,null);  
    }


    @isTest public static void test_historicQuery(){
        summaryTask st = new summaryTask(createSummaryObj('monthly - previous'));
        st.snapDate = date.newInstance(2022, 6, 30);
        st.specifiedSnapDate = true;
        string q = st.genHistoricQueryDates();
    }


    @isTest public static void test_normalStart(){
    	summaryTask.startnow();  
    }


    @isTest public static void test_settingNewSchedule(){
        string startTime = '|1:47';
        summaryTask.SummaryTaskInvocable(new list<string>{startTime});
    }


    @isTest public static void test_resetToday(){
    	summaryTask.resetToday();    
    }


    @isTest public static void test_getRelInfo(){
        summaryTask.getRelInfo('account', 'contact');
    }


    @isTest public static void get_tuneWhereClause(){
        string w = ' where account.name = :hello and lastname = bonzo ';
    	summaryTask.tuneWhereClause(w);    
    }
    

    @isTest public static void test_fyStartMonth(){
    	integer fyStart = summaryTask.fyStartMonth;    
    }
        

    @isTest private static void test_runToday(){
        summaryTask st = new summaryTask(null);
        st.snapDateField = 'snap field';

        Data_Summary__c ds = new Data_Summary__c();
        ds.Process_Data__c = 'daily';
        st.runToday(ds);

        ds.Process_Data__c = null;
        for (string f : frequencies){
            ds.Frequency__c = f;
            st.runToday(ds);
        }
    }


    public static void createSummaryPlan(id dsID){
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        Data_Summary_Field__c one = new Data_Summary_Field__c();
        one.Summary__c = dsID;
        one.Source_Field__c = 'id';
        one.How_to_Summarize__c = 'count'; 
        one.target_field__c = 'amount';
        // one.Target_Field_Type__c = 'integer';
        one.Reset_Value_After_Snapshot__c = TRUE;
        fields.add(one);   
        
        // Data_Summary_Field__c two = new Data_Summary_Field__c();
        // two.Summary__c = dsID;
        // two.Source_Field__c = 'Amount';
        // two.How_to_Summarize__c = 'Sum'; 
        // two.target_field__c = 'Probability';
        // // two.Target_Field_Type__c = 'integer';     
        // two.Reset_Value_After_Snapshot__c = TRUE;
        // fields.add(two);
         
        Data_Summary_Field__c three = new Data_Summary_Field__c();
        three.Summary__c = dsID;
        three.Source_Field__c = 'birthdate';
        three.How_to_Summarize__c = 'min'; 
        three.target_field__c = 'closedate';
        // three.Target_Field_Type__c = 'date';        
        three.Reset_Value_After_Snapshot__c = TRUE;
        fields.add(three);

        Data_Summary_Field__c four = new Data_Summary_Field__c();
        four.Summary__c = dsID;
        four.Source_Field__c = 'birthdate';
        four.How_to_Summarize__c = 'max'; 
        four.target_field__c = 'closedate';
        // four.Target_Field_Type__c = 'date';        
        four.Reset_Value_After_Snapshot__c = TRUE;
        fields.add(four);
        
        Data_Summary_Field__c five = new Data_Summary_Field__c();
        five.Summary__c = dsID;
        five.Source_Field__c = 'name';
        five.How_to_Summarize__c = 'copy (including blanks)'; 
        five.target_field__c = 'name';
        // five.Target_Field_Type__c = 'string';        
        fields.add(five);

        insert fields;
    }
    
    public static id createSummaryObj(string freq){
        Data_Summary__c ds = new Data_Summary__c();
        ds.Parent_Object__c = 'Account';
        ds.Child_Object__c = 'Contact';
        ds.Child_Relationship_Name__c = 'Contacts';
        ds.Relationship_Field_Child__c = 'AccountID';
        ds.Frequency__c = 'FY - Current';
        if ( !string.isblank(freq) ) ds.frequency__c = freq;
        ds.Date_Field_on_Child_Record__c = 'Birthdate';
        ds.Snapshot_Object__c = 'Opportunity';
        ds.Snapshot_Date_Field__c = 'closedate';
        ds.where_clause__c = 'lastname != null';
        ds.active__c = true;
        insert ds;
        return ds.id;
    }
    
    public static id getRecordTypeID(string obj, string name){
		id ret = null;
		for (RecordType rt : [select id, sObjectType, name from recordtype]){
			if (rt.sObjectType == obj && rt.name == name) {
				ret = rt.id;
				break;
			}
		}
		return ret;
    }

    public static id setupEchoTest(){
        Data_Summary__c ds = new Data_Summary__c();
        ds.Description__c = 'test';
        ds.Parent_Object__c = 'Account';
        ds.Frequency__c = 'Daily - Current';
        ds.Snapshot_Object__c = 'opportunity';
        ds.Snapshot_Date_Field__c = 'closedate';
        ds.where_clause__c = 'id != null';
        ds.Snapshot_As_Of_Date__c = date.today();
        ds.active__c = true;
        insert ds;
         
        list<Data_Summary_Field__c> fields = new list<Data_Summary_Field__c>();
        Data_Summary_Field__c one = new Data_Summary_Field__c();
        one.Summary__c = ds.id;
        one.Source_Field__c = 'name';
        one.target_field__c = 'name';
        fields.add(one);   
        insert fields;

        return ds.id;
    }
}