force-app/main/default/objects/Data_Summary__c/Data_Summary__c.object-meta.xml
<CustomObject>
    <label>Data Summary Task</label>
    <nameField>
        <displayFormat>ds-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <label>Child Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <inlineHelpText>The object that serves as the &quot;root&quot; of all data to be analyzed.  Often this will be the Contact object</inlineHelpText>
    <label>Parent Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary__c/fields/Snapshot_Object__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_Object__c</fullName>
    <inlineHelpText>The object where snapshots will be created</inlineHelpText>
    <label>Snapshot Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/Data_Summary_Field__c.object-meta.xml
<CustomObject>
    <label>Data Summary Field</label>
    <nameField>
        <displayFormat>dsf-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary_Field__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <formula>if (!isblank(Summary__r.Child_Object__c), Summary__r.Child_Object__c, Summary__r.Parent_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Child Object, as set on the Summary Task</inlineHelpText>
    <label>Child Object (as set on the task)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field (on Child)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary Task</label>
    <referenceTo>Data_Summary__c</referenceTo>
    <relationshipLabel>Data Summary Fields</relationshipLabel>
    <relationshipName>Data_Summary_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>The field where the analysis will be stored</inlineHelpText>
    <label>Summarize To (Target Field)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataSummaryFieldHandler_test.cls
/*
*  Steve Berley - steve@leftpropeller.com
*/
@isTest
private class DataSummaryFieldHandler_test {
    
    @isTest static void test_all(){
        Data_Summary__c ds = new Data_Summary__c(Parent_Object__c='Account', Child_Object__c='Contact', Snapshot_Object__c='opportunity');
        insert ds;

        Data_Summary_Field__c dsf = new Data_Summary_Field__c(summary__c=ds.id, Target_Field__c='name', Source_Field__c='lastname');
        insert dsf;
    }
}