force-app/main/default/objects/Data_Summary_Field__c/Data_Summary_Field__c.object-meta.xml
<CustomObject>
    <label>Data Summary Field</label>
    <nameField>
        <displayFormat>dsf-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Summary Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Summary_Field__c/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <formula>if (!isblank(Summary__r.Child_Object__c), Summary__r.Child_Object__c, Summary__r.Parent_Object__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The Child Object, as set on the Summary Task</inlineHelpText>
    <label>Child Object (as set on the task)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field (on Child)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Source_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Field_Type__c</fullName>
    <label>Source Field Type (raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Summarize_To_Object__c.field-meta.xml
<CustomField>
    <fullName>Summarize_To_Object__c</fullName>
    <formula>if ( Summary__r.Snapshot_Mode__c = true, Summary__r.Snapshot_Object__c , Summary__r.Parent_Object__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Summarizing To (Object)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>The field where the analysis will be stored</inlineHelpText>
    <label>Summarize To (Target Field)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Summary_Field__c/fields/Target_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Field_Type__c</fullName>
    <label>Target Field Type (raw)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataSummaryFieldHandler.cls
/*
*  Steve Berley - steve@leftpropeller.com
*/ 
public with sharing class DataSummaryFieldHandler { 
    // public DataSummaryFieldHandler() {    }

    public static void autoSetFields(Data_Summary_Field__c dsf){
        dsf.Target_Field_Type__c = lpTools.getFieldType(dsf.Summarize_To_Object__c, dsf.Target_Field__c);
        dsf.Source_Field_Type__c = lpTools.getFieldType(dsf.Child_Object__c, dsf.Source_Field__c);
    }
}